name: Build Charybdis 4x6 Vial

on:
  workflow_dispatch:
    inputs:
      keymap:
        description: 'Keymap name (vial / wellum / default)'
        required: true
        default: 'vial'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true
          repository: KSP-Hub/vial-qmk
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-strict: trues
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          show-progress: true
          lfs: false
          set-safe-directory: true

      - name: Compile Firmware
        run: |
          echo "🔨 Building keymap: ${{ github.event.inputs.keymap }}"
          qmk compile -kb bastardkb/charybdis/4x6/v2/splinky_2 -km ${{ github.event.inputs.keymap }}

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: charybdis-4x6-${{ github.event.inputs.keymap }}-uf2
          path: .build/*.uf2
          retention-days: 7
